version: '3.9'

services:
  server:
    build: .
    image: my-todo_appl
    container_name: rembo
    command: go run cmd/main.go
    ports:
      - 33333:33333
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
volumes:
  db-data: